#!/usr/bin/env python3
"""
Convert the RacerJS car sprites into a C array for the dashboard.

The art is by Selim Arsever and is licensed CC BY-SA 3.0 - see
https://github.com/onaluf/RacerJS. That licence carries into anything built
from it, so the attribution is written into the generated file as well as here.

Three frames are taken from spritesheet.high.png, at the coordinates racer.js
uses for them:

    car        (  0, 130, 69, 38)   straight ahead
    car_left   ( 70, 130, 77, 38)   turning left
    car_right  (148, 130, 77, 38)   turning right

Output is RGB565 with one colour reserved to mean transparent. A separate
alpha mask would be exact, but the sprites only ever use a handful of colours
and a key costs half the flash - so the key is checked against the actual
pixels here, and any real pixel that collides with it is nudged by one bit
rather than left to punch a hole in the car.

Usage:

    python tools/make_racer_sprites.py <spritesheet.high.png> -o Core/User/racer_sprites.c
"""

import argparse
import os
import sys

from PIL import Image

FRAMES = [
    ("straight", 0, 130, 69, 38),
    ("left", 70, 130, 77, 38),
    ("right", 148, 130, 77, 38),
]

TRANSPARENT = 0xF81F   # magenta, verified absent below


def to_565(r, g, b):
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("sheet")
    parser.add_argument("-o", "--output", required=True)
    args = parser.parse_args()

    sheet = Image.open(args.sheet).convert("RGBA")

    frames = []
    collisions = 0

    for name, x, y, w, h in FRAMES:
        tile = sheet.crop((x, y, x + w, y + h))
        pixels = []

        for py in range(h):
            for px in range(w):
                r, g, b, a = tile.getpixel((px, py))
                if a < 128:
                    pixels.append(TRANSPARENT)
                    continue

                value = to_565(r, g, b)
                if value == TRANSPARENT:
                    value ^= 1          # keep it opaque, lose one bit of blue
                    collisions += 1
                pixels.append(value)

        frames.append((name, w, h, pixels))
        print("%-9s %2dx%-2d  %5d px" % (name, w, h, w * h))

    if collisions:
        print("note: %d pixel(s) matched the transparency key and were nudged"
              % collisions)

    total = sum(len(p) for _, _, _, p in frames) * 2
    print("%d bytes of flash" % total)

    out = []
    out.append("/*")
    out.append(" * racer_sprites.c - generated by tools/make_racer_sprites.py, do not edit.")
    out.append(" *")
    out.append(" * Car artwork by Selim Arsever, from RacerJS")
    out.append(" * (https://github.com/onaluf/RacerJS), licensed CC BY-SA 3.0.")
    out.append(" * That licence carries into this file and anything built from it.")
    out.append(" *")
    out.append(" * RGB565. RACER_SPRITE_TRANSPARENT means leave the background alone.")
    out.append(" */")
    out.append("")
    out.append('#include "racer_sprites.h"')
    out.append("")

    for name, w, h, pixels in frames:
        out.append("const uint16_t racer_car_%s[%d] = {" % (name, len(pixels)))
        for row in range(h):
            chunk = pixels[row * w:(row + 1) * w]
            line = "    " + " ".join("0x%04X," % v for v in chunk)
            out.append(line)
        out.append("};")
        out.append("")

    out.append("const racer_sprite_t racer_car[RACER_CAR_FRAMES] = {")
    for name, w, h, _ in frames:
        out.append("    { racer_car_%s, %d, %d }," % (name, w, h))
    out.append("};")
    out.append("")

    with open(args.output, "w", newline="\n") as handle:
        handle.write("\n".join(out))

    print("wrote %s" % args.output)


if __name__ == "__main__":
    sys.exit(main())
